default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: indeva_development
  username: postgres
  password: root
  host: localhost

test:
  <<: *default
  database: indeva_test
  username: postgres
  password: root
  host: localhost

production:
  <<: *default
  database: indeva_production
  username: indeva
  password: <%= ENV['INDEVA_DATABASE_PASSWORD'] %>
